#!/bin/bash
# Search utility based on fzf and plain grep

# Configurations
SEARCH_EXTENSIONS="'*.md,*.txt'"
SEARCH_DEFAULT_DIR="$WS"

SEARCH_DIR=$1

if [[ "$SEARCH_DIR" == "" ]]; then
  SEARCH_DIR="$SEARCH_DEFAULT_DIR"
fi

echo $SEARCH_DIR

RESULT=$( \
  grep --include='*.md' --line-buffered --color=never -rn "" $SEARCH_DIR \
  | fzf | cut -d ':' -f -2 | awk -F ':' '{printf "+%s %s\n", $2, $1}')

if [[ "$RESULT" != "" ]]; then
  vim -R $RESULT
fi
