" vimrc
" author: terxor

" --- OPTIONS ---
syntax on                      " syntax highlighting
set nocompatible               " compatible with vi? no
set background=light           " affects colors
set notermguicolors            " we use terminal colors with xv3_light
set hidden                     " allow modified unsaved buffers
set encoding=utf-8             " allow a variety of characters
set relativenumber             " relative line numbers
set incsearch                  " search as you type
set ignorecase                 " ignore case
set smartcase                  " case sensitive search on mixed case
set hlsearch                   " highlight the matching patterns
set ruler                      " show line num, col in status bar
set wildmenu                   " shows options on tab in commands
set wildmode=longest:full,full " better options list
set wildoptions=pum            " show pop-up-menu
set nowrap                     " do not wrap lines
set tabstop=2                  " tab is 2 spaces
set softtabstop=2              " insert tab as 2 spaces
set shiftwidth=2               " indents are two spaces
set expandtab                  " use spaces instead of tab char
set gdefault                   " substitute flag ':s///g' by default
set timeout                    " timeout on mapped key sequences
set timeoutlen=300             " how long to wait, find the right balance
set ttimeoutlen=1              " to make escape faster
set showmode                   " shows whether in insert/visual/replace mode
set showcmd                    " show partial commands below status line
set autoread                   " auto-reload modified buffers in some cases
set updatecount=0              " disable swap files
set belloff=all                " turn off terminal bell
set splitright                 " put the new window right of the current one
set splitbelow                 " put the new window below the current one
set autoindent                 " preserve indentation on next line
set foldmethod=marker          " fold content inside marker (see foldmarker)
set cursorline                 " easier to spot which line we are at
set tildeop                    " use motions with tilde (swap case)
color xv3_light

" --- MAPPINGS ---
let mapleader = " "
map ; $

" Quick exit and save
nnoremap <leader>q :qa<CR>
nnoremap <leader>w :w<CR>
nnoremap <leader>d :bd<CR>

" For fzf-vim
nnoremap <leader>e :Files<CR>
nnoremap <leader>b :Buffers<CR>
nnoremap <leader>f :Lines<CR>
nnoremap <leader>s :Rg ''<CR>

" Quick copy (with motion), direct copy in visual mode
nnoremap <leader>y "+y
vnoremap <leader>y "+y

" Quick paste, replaces text in visual mode
nnoremap <leader>p "+p
vnoremap <leader>p "+p

" Smarter replace
vnoremap <leader>r y:<C-u>%s/<C-r>"/<C-r>"
nnoremap <leader>r :%s/<C-r><C-w>/<C-r><C-w>

" Use tab and shift-tab to cycle through buffers
nnoremap <tab> :bn<CR>
nnoremap <s-tab> :bp<CR>

" Hide other windows
nnoremap <leader>o :only<CR>

" clear search by searching for empty string
nnoremap <leader>/ :let @/=''<CR>

" Quick swapcase in word (W)
nnoremap <leader>c viW~

cnoremap <c-k> <up>
cnoremap <c-j> <down>

source $HOME/.vim/status.vim
source $HOME/.vim/util.vim
source $HOME/.vim/filetype.vim
source $HOME/.vim/custom.vim

